colors:
  bg:         "1c1c1c"
  bg0:        "1c1c1c"
  bg1:        "32302f"
  bg2:        "504945"
  bg3:        "665c54"
  bg4:        "7c6f64"

  fg:         "ebdbb2"
  fg0:        "fbf1c7"
  fg1:        "ebdbb2"
  fg2:        "d5c4a1"
  fg3:        "bdae93"
  fg4:        "a89984"

  red:        "ea6962"
  green:      "a9b665"
  yellow:     "e8b667"
  blue:       "7daea3"
  purple:     "d3869b"
  aqua:       "89b482"
  orange:     "d8a657"
  gray:       "a89984"

  alt_red:    "fa7972"
  alt_green:  "b9c675"
  alt_yellow: "e396ab"
  alt_blue:   "8dbeb3"
  alt_purple: "e396ab"
  alt_aqua:   "99c492"
  alt_orange: "fe8019"
  alt_gray:   "928374"

core:
  normal_text:
    foreground: fg
    background: bg

  regular_file:
    foreground: fg
    background: bg

  reset_to_normal: {}

  directory:
    foreground: blue

  symlink:
    foreground: alt_blue
    font-style: italic

  multi_hard_link:
    font-style: bold

  fifo:
    foreground: purple

  socket:
    foreground: purple
    font-style: bold

  door:
    foreground: alt_purple
    font-style: bold

  block_device:
    foreground: yellow
    font-style: bold

  character_device:
    foreground: alt_yellow
    font-style: italic

  broken_symlink:
    foreground: alt_red
    font-style: italic

  missing_symlink_target:
    foreground: fg
    background: alt_red

  setuid:
    foreground: fg
    background: red

  setgid:
    foreground: bg
    background: orange

  file_with_capability:
    foreground: bg
    background: red

  sticky_other_writable:
    foreground: fg
    background: blue
    font-style: italic

  other_writable:
    foreground: alt_green
    font-style: bold

  sticky:
    foreground: fg
    background: blue

  executable_file:
    foreground: alt_green
    font-style: bold

text:
  special:
    foreground: alt_yellow
    font-style: bold

  todo:
    foreground: alt_green

  licenses:
    foreground: fg1
    font-style: italic

  configuration:
    foreground: alt_yellow

  other:
    foreground: fg

markup:
  foreground: yellow

programming:
  source:
    foreground: green

  tooling:
    foreground: alt_green
    font-style: italic

    continuous-integration:
      foreground: alt_blue

media:
  foreground: aqua

  video:
    foreground: alt_aqua
    font-style: bold

office:
  foreground: alt_blue
  font-style: bold

archives:
  foreground: orange

  images:
    foreground: alt_orange
    font-style: bold

executable:
  foreground: alt_green
  font-style: bold

unimportant:
  foreground: bg3
  font-style: italic
